### Numpy as np in Python 
NumPy (Numerical Python) is a Python library used for working with numbers, arrays, and mathematical operations. It is much faster and more efficient than Python lists for numerical computations.<br><h5>
NumPy is a Python library that provides support for large, multi-dimensional arrays and matrices, along with mathematical functions to perform fast numerical calculations.</h5>

In [ ]:
# creating arr
new =np.random.randint(1,11,size=(3,3))
new

In [2]:

""" 1D array : """

import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [ ]:

"""Reshaping the array """
arr2 = np.array([1,2,3,4])
arr2.reshape(2,2)

#  note -- reshape means creating number of row and column making 2D one D array


array([[1, 2],
       [3, 4]])

In [ ]:
## 2d
arr1 = np.array([[1,2,3,4]])
print(arr1)
print(arr1.shape)

[[1 2 3 4]]
(1, 4)


In [ ]:

""" 2D Array """
import numpy as np
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)
print(arr2.shape)

# note -- .shape means size of array (2x4)

# note -- for to make 2D array we should give double [[]] it make 2D array

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)


In [2]:

## In - built function in numpy 
## using arange function

import numpy as np

arr = np.arange(0,10,2)
print(arr)
print(arr.reshape(5,1))    #it will create 2D array



[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [ ]:

# ones in built function

arr = np.ones((3,4))
print(arr)

# note -- .ones (()) we should make double braket for to create 2D array. o

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:

# eye = for to make identity matrix

arr = np.eye(3,3)
print(arr)
print(arr.ndim)    # dimenision
# note -- while creating identity matrix we should use only single bracket () 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2


In [3]:

## array,shape,dimension,dtype,itemsize,size

arr = np.array([[2,4,6],[1,3,5]])

print(f"Array : {arr}")
print(f"Size of Array :{arr.size}")
print(f"Dimenision of Array : {arr.ndim}D")
print(f"Shape of Array : {arr.shape}")
print(f"Data type of array : {arr.dtype}")   # which type of element is belong to 
print(f"Data Type (in byte) : {arr.itemsize}")  # size of one element

Array : [[2 4 6]
 [1 3 5]]
Size of Array :6
Dimenision of Array : 2D
Shape of Array : (2, 3)
Data type of array : int64
Data Type (in byte) : 8


In [5]:

""" Array vecotorized method : """

arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

# addition :
print(arr1+arr2)

# Subtraction :
print(arr1-arr2)

# multiplication : 
print(arr1*arr2)

# Division :
print(arr1/arr2)

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]


In [7]:

""" Universal function : """

arr1 = np.array([4,9,16,25])

#square
print(np.sqrt(arr1))

#Expontinal 
print(np.exp(arr1))

# Sine 
print(np.sin(arr1))

# Natural Log
print(np.log(arr1))

[2. 3. 4. 5.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10]
[-0.7568025   0.41211849 -0.28790332 -0.13235175]
[1.38629436 2.19722458 2.77258872 3.21887582]


In [31]:
#universal Function (ufunc)

""" Array Slice and Indexing """

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(f"First ELement : {arr[0,0]}")
print(f"Middle ELement : {arr[1,1]}")
print(f"last ELement : {arr[2,3]}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First ELement : 1
Middle ELement : 6
last ELement : 12


In [ ]:

#slicing method 

print(arr[1:])
print()
print(arr[2:3])
print()
print(arr[0:1])
print()
print(arr[1:2])
print()
print(arr[:2,1:3])
print()
print(arr[1:,1:3])
print()
print(arr[1:,0:2])

# note -- slicing method last :3 also print but 1: this value doesnot print 

[[ 5  6  7  8]
 [ 9 10 11 12]]

[[ 9 10 11 12]]

[[1 2 3 4]]

[[5 6 7 8]]

[[2 3]
 [6 7]]

[[ 6  7]
 [10 11]]
[[ 5  6]
 [ 9 10]]


In [ ]:

## Replacing value :

arr[1:,1:3] = 7
print(arr)
print()
arr[0:,0:] = 7
print(arr)

[[ 1  2  3  4]
 [ 5  7  7  8]
 [ 9  7  7 12]]

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
## Statitical Concept -- normalization 

# to have mean 0 and standard deviation 1 

data = np.array([1,2,3,4,5])

# calculating mean and standard devition 

mean = np.mean(data)
std_d= np.std(data)

# calculating normalization 

normal = (data-mean)/std_d
print(f"Normalization : {normal}")


Normalization : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [38]:


# Some statical method 

data = np.array([i for i in range(1,11)])
print(data)

# mean 
mean = np.mean(data)
print(f"\n Mean : {mean}")

# standard Deviation 
std_d = np.std(data)
print(f"\n Standard Deviation : {std_d}")

# median 
med = np.median(data)
print(f"\n Median : {med}")

# vairance
var = np.var(data)
print(f"\n variance : {var}")
 



[ 1  2  3  4  5  6  7  8  9 10]

 Mean : 5.5

 Standard Deviation : 2.8722813232690143

 Median : 5.5

 variance : 8.25


In [50]:

#  some logical operation :

data = np.array([i for i in range(1,11)])

print(data[data>5])
print(data[(data>5) & (data<9)])

# note -- we should use this (&) instead of this(and)


[ 6  7  8  9 10]
[6 7 8]
