In [2]:
import numpy as np

### Module: NumPy Assignments
#### Lesson: NumPy
#### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [20]:

arr_5x5 = np.random.randint(1,21,size=(5,5))
print(arr_5x5)
arr_5x5[2:3] = 1
print()
print(arr_5x5)

[[11  1  2  1 15]
 [14 13 17 18 14]
 [12  5 17 19 15]
 [ 4  4  7 20  2]
 [ 8 13 13  6 13]]

[[11  1  2  1 15]
 [14 13 17 18 14]
 [ 1  1  1  1  1]
 [ 4  4  7 20  2]
 [ 8 13 13  6 13]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [22]:
# Replacing the 3 row with one only 

arr_4x4 = np.random.randint(1,21,size=(4,4))

print(arr_4x4)
print()
np.fill_diagonal(arr_4x4,0)
print(arr_4x4)



[[ 6  2 11  6]
 [ 3 12 10  6]
 [ 9 12  1 15]
 [ 2 17  3 19]]

[[ 0  2 11  6]
 [ 3  0 10  6]
 [ 9 12  0 15]
 [ 2 17  3  0]]


#### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [5]:
arr6x6 = np.random.randint(1,37,size=(6,6))
print(arr6x6)
print()
print(arr6x6[2:5])
print()
print(arr6x6[0:,1:4])

[[24 18 29 30  7 30]
 [ 1 33 18 22 34 11]
 [28 20  5 14 19 20]
 [35 14 28 29 35 34]
 [10 35 34  4 18  3]
 [11  7 13 12 33 34]]

[[28 20  5 14 19 20]
 [35 14 28 29 35 34]
 [10 35 34  4 18  3]]

[[18 29 30]
 [33 18 22]
 [20  5 14]
 [14 28 29]
 [35 34  4]
 [ 7 13 12]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [22]:
arr = np.random.randint(1,10,size=(5,5))
print(arr)
print()
border = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print(border)

[[8 8 3 9 4]
 [1 8 8 9 6]
 [5 2 4 5 5]
 [8 6 3 9 3]
 [5 8 9 2 9]]

[8 8 3 9 4 5 8 9 2 9 1 5 8 6 5 3]


#### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [24]:

arr1 = np.random.randint(1,10,size=(3,4))
arr2 = np.random.randint(1,10,size=(3,4))

print("Addition : ")
print(arr1+arr2)
print()
print("Subtraction : ")
print(arr1-arr2)
print()
print("Multiplication : ")
print(arr1*arr2)
print()
print("Division : ")
print(arr1/arr2)

Addition : 
[[ 7 11  5 18]
 [15 13 14 17]
 [15  8 16  7]]

Subtraction : 
[[-5 -7  3  0]
 [ 3  3  0  1]
 [ 1 -2 -2  5]]

Multiplication : 
[[ 6 18  4 81]
 [54 40 49 72]
 [56 15 63  6]]

Division : 
[[0.16666667 0.22222222 4.         1.        ]
 [1.5        1.6        1.         1.125     ]
 [1.14285714 0.6        0.77777778 6.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [28]:

arr = np.random.randint(1,10,size=(4,4))
print(arr)
print()

row_wise = np.sum(arr,axis=0)      # 0 - means row
col_wise = np.sum(arr,axis=1)      # 1 - means column

print("Row - wise addition : ",row_wise)
print("Col - wise subtraction : ",col_wise)

[[5 7 8 6]
 [6 1 4 8]
 [5 6 8 9]
 [6 2 6 7]]

Row - wise addition :  [22 16 26 30]
Col - wise subtraction :  [26 19 28 21]


#### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [33]:
arr = np.random.randint(1,10,size=(5,5))
print(arr)
print()
print("Mean of array : ",np.mean(arr))
print("Medain of array : ",np.median(arr))
print("Standard deviation : ",np.std(arr))
print("Variance of arr : ",np.var(arr))



[[2 7 7 9 4]
 [4 8 5 5 2]
 [2 2 6 4 1]
 [4 1 5 7 5]
 [9 1 8 7 1]]

Mean of array :  4.64
Medain of array :  5.0
Standard deviation :  2.5904439773907484
Variance of arr :  6.7104


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [35]:

arr = np.random.randint(1,10,size=(3,3))
print(arr)
print()

mean  = np.mean(arr)
std_dev = np.std(arr)

normalization = (arr-mean)/std_dev

print("normalization")
print(normalization) 


[[7 7 2]
 [5 7 6]
 [5 6 7]]

normalization
[[ 0.78975397  0.78975397 -2.44105774]
 [-0.50257071  0.78975397  0.14359163]
 [-0.50257071  0.14359163  0.78975397]]


#### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [37]:
arr = np.random.randint(1,10,size=(3,3))
arr1 = np.random.randint(1,10,size=(3))

print(arr)
print()
print(arr1)
print()

print("Addition of 1D and 2D array : ")
print(arr+arr1)


[[4 1 7]
 [5 8 1]
 [1 2 5]]

[2 5 9]

Addition of 1D and 2D array : 
[[ 6  6 16]
 [ 7 13 10]
 [ 3  7 14]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [39]:

arr = np.random.randint(1,10,size=(4,4))
arr1 = np.random.randint(1,10,size=(4,))

print(arr)
print()
print(arr1)

print("Subtracting 1D array with each col of 2D array")

sub = arr-arr1[:,np.newaxis]

print(sub)

#  note -- arr1[:,np.newaxis] it help to changes row to col 

[[8 3 9 2]
 [7 3 6 3]
 [6 2 2 4]
 [4 5 2 5]]

[6 3 3 8]
Subtracting 1D array with each col of 2D array
[[ 2 -3  3 -4]
 [ 4  0  3  0]
 [ 3 -1 -1  1]
 [-4 -3 -6 -3]]


#### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [ ]:

arr = np.random.randint(1,10,size=(3,3))

print("Matrix : ")
print(arr)

# calculating det

print()
det = np.linalg.det(arr)
print("Determination of Matrix : ",det)

# inverse

print()
inv = np.linalg.inv(arr)
print("Inverse of matrix : ")
print(inv)

# eigenvalues 

print()
eig = np.linalg.eigvals(arr)
print("Eigenvalues : ")
print(eig)


# note -- (linalg) It is a NumPy module that provides functions for linear algebra and matrix operations.


Matrix : 
[[5 1 8]
 [9 3 6]
 [2 7 1]]

Determination of Matrix :  263.99999999999994

Inverse of matrix : 
[[-0.14772727  0.20833333 -0.06818182]
 [ 0.01136364 -0.04166667  0.15909091]
 [ 0.21590909 -0.125       0.02272727]]

Eigenvalues : 
[13.64331128+0.j         -2.32165564+3.73631587j -2.32165564-3.73631587j]



2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [8]:

A = np.random.randint(1,10,size=(2,3))
B = np.random.randint(1,10,size=(3,2))

print("Matrix A : ")
print(A)
print()
print("Matrix B : ")
print(B)
print()

mul = np.dot(A,B)
print("Matrix Multiplication : ")
print(mul)


Matrix A : 
[[4 1 6]
 [6 1 6]]

Matrix B : 
[[1 2]
 [2 8]
 [1 4]]

Matrix Multiplication : 
[[12 40]
 [14 44]]


#### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [ ]:

arr = np.random.randint(1,10,size=(3,3))

print(arr)
print()
print("Reshaping (1,9) : ")
print(arr.reshape(1,9))            # note -- (no.of row , number of element or col)
print()
print("Reshaping (9,1)")
print(arr.reshape(9,1))

[[9 5 1]
 [1 9 9]
 [9 6 7]]

Reshaping (1,9) : 
[[9 5 1 1 9 9 9 6 7]]

Reshaping (9,1)
[[9]
 [5]
 [1]
 [1]
 [9]
 [9]
 [9]
 [6]
 [7]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [17]:

arr = np.random.randint(1,10,size=(5,5))

print(arr)
print()
print("Faltern")
print(arr.flatten())
print()
print("Reshaping (5,5) :")
print(arr.reshape(5,5))

[[2 3 5 6 1]
 [3 8 4 5 2]
 [7 6 7 5 1]
 [7 7 3 1 1]
 [7 2 4 6 3]]

Faltern
[2 3 5 6 1 3 8 4 5 2 7 6 7 5 1 7 7 3 1 1 7 2 4 6 3]

Reshaping (5,5) :
[[2 3 5 6 1]
 [3 8 4 5 2]
 [7 6 7 5 1]
 [7 7 3 1 1]
 [7 2 4 6 3]]


#### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [ ]:

arr = np.random.randint(1,10,size=(5,5))

print(arr)
print()

corner = arr[[0,0,-1,-1],[0,-1,0,-1]]    # [[row][col]]
print(corner)

[[1 5 5 6 5]
 [9 4 2 2 5]
 [9 2 5 6 1]
 [6 5 3 7 8]
 [6 5 6 2 3]]

[1 5 6 3]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [ ]:

arr = np.random.randint(1,21,size=(4,4))

print(arr)
print()

arr[arr>10] = 10
print("Greater than 10 :")
print(arr)



[[18  4 11 20]
 [ 3 10  3  7]
 [ 5 13  7 15]
 [ 9 17  2  1]]

Greater than 10 :
[[10  4 10 10]
 [ 3 10  3  7]
 [ 5 10  7 10]
 [ 9 10  2  1]]


#### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [49]:

#  [(field_name , data type)]

data_f = [('name','U10'),('age','i4'),('weight','f4')]   
data = np.array([('Sabin rai',45,68.22),('Sabin Rai',42,99.44),('Ram Karki',33,99.32)],dtype=data_f)
print(data)
print()
# sorting 

sort_by = np.sort(data,order='age')
print("sorted By the age : ")
print(sort_by)

[('Sabin rai', 45, 68.22) ('Sabin Rai', 42, 99.44)
 ('Ram Karki', 33, 99.32)]

sorted By the age : 
[('Ram Karki', 33, 99.32) ('Sabin Rai', 42, 99.44)
 ('Sabin rai', 45, 68.22)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [5]:

data_f = [('x','i4'),('y','i4')]
data = np.array([(4,6),(9,1),(3,3)],dtype=data_f)
print(data)
print()

#  compute the eucliden distance between the each pair 

distance = np.sqrt((data['x'][:,np.newaxis] - data['x'])**2 + (data['y'][:,np.newaxis] - data['y'])**2)
print("Ecucliden Distance : ")
print(distance)

[(4, 6) (9, 1) (3, 3)]

Ecucliden Distance : 
[[0.         7.07106781 3.16227766]
 [7.07106781 0.         6.32455532]
 [3.16227766 6.32455532 0.        ]]



#### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [4]:
import numpy.ma as ma

In [13]:

arr = np.random.randint(1,21,size=(4,4))
masked_arr = ma.masked_greater(arr,10)
print(arr)
print()
print(masked_arr)
print()

print("Sum of unmarks Array : ")
print(masked_arr.sum())




[[ 2  2  4 13]
 [16  4 18  3]
 [ 6  9  2  5]
 [ 7 17  8 18]]

[[2 2 4 --]
 [-- 4 -- 3]
 [6 9 2 5]
 [7 -- 8 --]]

Sum of unmarks Array : 
52


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [5]:


arr = np.random.randint(1,10,size=(3,3))

masks_arr = ma.masked_array(arr,mask=np.eye(3,dtype=bool))

print(arr)
print()
print(masks_arr)
print()

unmasked_mean = masks_arr.mean()

masks_arr = masks_arr.filled(unmasked_mean)
print(masks_arr)

[[5 9 1]
 [1 6 5]
 [5 6 9]]

[[-- 9 1]
 [1 -- 5]
 [5 6 --]]

[[4 9 1]
 [1 4 5]
 [5 6 4]]
